name: ci
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  
jobs:
  publish-paimon-docker:
    if: >-
      (
        github.event_name == 'pull_request' &&
        github.event.pull_request.head.repo.full_name == github.repository
      ) || (
        github.event_name == 'pull_request_target' &&
        github.event.pull_request.head.repo.full_name != github.repository
      ) || (
        github.event_name == 'push' &&
        github.event.pull_request.head.repo.full_name == github.repository
      )
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get branch name
        run: echo "branch_name=$(echo ${GITHUB_HEAD_REF:-${GITHUB_REF#refs/*/}} | tr / -)" >> $GITHUB_ENV
      - name: Build and push Paimon Docker image
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
          registry: ghcr.io
          build_args: GITHUB_TOKEN=${{ secrets.DSP_REPO_TOKEN }}
          tags: ${{ env.branch_name }}
